dist: bionic
compiler: clang

addons:
  apt:
    packages:
    - ninja-build

before_install:
  - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protobuf-cpp-3.9.1.tar.gz | tar zx
    && pushd protobuf-3.9.1
    && ./configure
    && make install
    && popd
  - go get github.com/uber/prototool/cmd/prototool
  - go get github.com/golang/protobuf/protoc-gen-go
  - prototool version

script: ./build
