dist: bionic
compiler: clang

addons:
  apt:
    packages:
    - ninja-build

before_install:
  - git clone -b 'v1.20.0' https://github.com/grpc/grpc
  - pushd grpc
    && git submodule update --init
    && make
    && pushd third_party/protobuf
    && sudo make install
    && popd
    && sudo make install
    && popd
  - go get github.com/golang/protobuf/protoc-gen-go
  - go get github.com/uber/prototool/cmd/prototool
  - prototool version
  - protoc --version

script: ./build
