dist: bionic
compiler: clang

addons:
  apt:
    packages:
    - ninja-build
    - golang-goprotobuf-dev
    - protobuf-compiler-grpc

before_install:
  - go get github.com/uber/prototool/cmd/prototool
  - prototool version

script: ./build
