dist: bionic
compiler: clang

addons:
  apt:
    packages:
    - ninja-build
    - protobuf-compiler

before_install:
  - go get github.com/uber/prototool/cmd/prototool
  - prototool version
  - ${GOPATH}/bin/prototool version

script: ./build
