// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blinkt.proto

package blinkt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pixel_Brightness int32

const (
	Pixel_Off     Pixel_Brightness = 0
	Pixel_Low     Pixel_Brightness = 1
	Pixel_Medium  Pixel_Brightness = 2
	Pixel_Bright  Pixel_Brightness = 3
	Pixel_Maximum Pixel_Brightness = 4
)

var Pixel_Brightness_name = map[int32]string{
	0: "Off",
	1: "Low",
	2: "Medium",
	3: "Bright",
	4: "Maximum",
}

var Pixel_Brightness_value = map[string]int32{
	"Off":     0,
	"Low":     1,
	"Medium":  2,
	"Bright":  3,
	"Maximum": 4,
}

func (x Pixel_Brightness) String() string {
	return proto.EnumName(Pixel_Brightness_name, int32(x))
}

func (Pixel_Brightness) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9e454e6b290ede76, []int{1, 0}
}

type Response_Result int32

const (
	Response_Failure Response_Result = 0
	Response_Success Response_Result = 1
)

var Response_Result_name = map[int32]string{
	0: "Failure",
	1: "Success",
}

var Response_Result_value = map[string]int32{
	"Failure": 0,
	"Success": 1,
}

func (x Response_Result) String() string {
	return proto.EnumName(Response_Result_name, int32(x))
}

func (Response_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9e454e6b290ede76, []int{2, 0}
}

type Color struct {
	R                    uint32   `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G                    uint32   `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B                    uint32   `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Color) Reset()         { *m = Color{} }
func (m *Color) String() string { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()    {}
func (*Color) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e454e6b290ede76, []int{0}
}

func (m *Color) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Color.Unmarshal(m, b)
}
func (m *Color) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Color.Marshal(b, m, deterministic)
}
func (m *Color) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Color.Merge(m, src)
}
func (m *Color) XXX_Size() int {
	return xxx_messageInfo_Color.Size(m)
}
func (m *Color) XXX_DiscardUnknown() {
	xxx_messageInfo_Color.DiscardUnknown(m)
}

var xxx_messageInfo_Color proto.InternalMessageInfo

func (m *Color) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *Color) GetG() uint32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *Color) GetB() uint32 {
	if m != nil {
		return m.B
	}
	return 0
}

type Pixel struct {
	Index                uint32           `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Brightness           Pixel_Brightness `protobuf:"varint,2,opt,name=brightness,proto3,enum=Pixel_Brightness" json:"brightness,omitempty"`
	Color                *Color           `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Pixel) Reset()         { *m = Pixel{} }
func (m *Pixel) String() string { return proto.CompactTextString(m) }
func (*Pixel) ProtoMessage()    {}
func (*Pixel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e454e6b290ede76, []int{1}
}

func (m *Pixel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pixel.Unmarshal(m, b)
}
func (m *Pixel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pixel.Marshal(b, m, deterministic)
}
func (m *Pixel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pixel.Merge(m, src)
}
func (m *Pixel) XXX_Size() int {
	return xxx_messageInfo_Pixel.Size(m)
}
func (m *Pixel) XXX_DiscardUnknown() {
	xxx_messageInfo_Pixel.DiscardUnknown(m)
}

var xxx_messageInfo_Pixel proto.InternalMessageInfo

func (m *Pixel) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Pixel) GetBrightness() Pixel_Brightness {
	if m != nil {
		return m.Brightness
	}
	return Pixel_Off
}

func (m *Pixel) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

type Response struct {
	Result               Response_Result `protobuf:"varint,1,opt,name=result,proto3,enum=Response_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e454e6b290ede76, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() Response_Result {
	if m != nil {
		return m.Result
	}
	return Response_Failure
}

func init() {
	proto.RegisterEnum("Pixel_Brightness", Pixel_Brightness_name, Pixel_Brightness_value)
	proto.RegisterEnum("Response_Result", Response_Result_name, Response_Result_value)
	proto.RegisterType((*Color)(nil), "Color")
	proto.RegisterType((*Pixel)(nil), "Pixel")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("blinkt.proto", fileDescriptor_9e454e6b290ede76) }

var fileDescriptor_9e454e6b290ede76 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4f, 0x32, 0x31,
	0x10, 0xc6, 0x29, 0xb0, 0x0b, 0xef, 0xc0, 0x4b, 0x6a, 0x63, 0x0c, 0x41, 0x13, 0xcd, 0x9e, 0x48,
	0x34, 0x25, 0xac, 0xdf, 0x00, 0xa2, 0x27, 0x89, 0x66, 0xb9, 0x78, 0x65, 0xa1, 0x2c, 0x8d, 0xdd,
	0x2d, 0xe9, 0x9f, 0x80, 0x77, 0xbf, 0x91, 0x5f, 0xd0, 0xb4, 0x05, 0xd4, 0x9b, 0xb7, 0xf9, 0xcd,
	0xf3, 0xcc, 0x74, 0x3a, 0x03, 0xdd, 0x5c, 0xf0, 0xea, 0xcd, 0xd0, 0xad, 0x92, 0x46, 0x0e, 0x2e,
	0x0b, 0x29, 0x0b, 0xc1, 0x46, 0x9e, 0x72, 0xbb, 0x1e, 0xb1, 0x72, 0x6b, 0xde, 0x83, 0x98, 0x8c,
	0x21, 0x9a, 0x4a, 0x21, 0x15, 0xe9, 0x02, 0x52, 0x7d, 0x74, 0x83, 0x86, 0xff, 0x33, 0xe4, 0xa9,
	0xe8, 0xd7, 0x03, 0x15, 0x8e, 0xf2, 0x7e, 0x23, 0x50, 0x9e, 0x7c, 0x22, 0x88, 0x5e, 0xf8, 0x9e,
	0x09, 0x72, 0x0e, 0x11, 0xaf, 0x56, 0x6c, 0x7f, 0xa8, 0x0b, 0x40, 0xc6, 0x00, 0xb9, 0xe2, 0xc5,
	0xc6, 0x54, 0x4c, 0x6b, 0xdf, 0xa4, 0x97, 0x9e, 0x51, 0x5f, 0x41, 0x27, 0x27, 0x21, 0xfb, 0x61,
	0x22, 0x57, 0x10, 0x2d, 0xdd, 0x14, 0xfe, 0x91, 0x4e, 0x1a, 0x53, 0x3f, 0x53, 0x16, 0x92, 0xc9,
	0x14, 0xe0, 0xbb, 0x8e, 0xb4, 0xa0, 0xf1, 0xbc, 0x5e, 0xe3, 0x9a, 0x0b, 0x9e, 0xe4, 0x0e, 0x23,
	0x02, 0x10, 0xcf, 0xd8, 0x8a, 0xdb, 0x12, 0xd7, 0x5d, 0x1c, 0xbc, 0xb8, 0x41, 0x3a, 0xd0, 0x9a,
	0x2d, 0xf6, 0xbc, 0xb4, 0x25, 0x6e, 0x26, 0xaf, 0xd0, 0xce, 0x98, 0xde, 0xca, 0x4a, 0x33, 0x32,
	0x84, 0x58, 0x31, 0x6d, 0x85, 0xf1, 0x83, 0xf7, 0x52, 0x4c, 0x8f, 0x92, 0x0b, 0xac, 0x30, 0xd9,
	0x41, 0x4f, 0x12, 0x88, 0x43, 0xc6, 0x35, 0x7b, 0x5c, 0x70, 0x61, 0x15, 0xc3, 0x35, 0x07, 0x73,
	0xbb, 0x5c, 0x32, 0xad, 0x31, 0x4a, 0x3f, 0x10, 0xc4, 0x13, 0xbf, 0x70, 0x72, 0x0d, 0xed, 0x39,
	0x33, 0x61, 0x39, 0x71, 0xf8, 0xf2, 0xe0, 0xdf, 0xa9, 0x79, 0x52, 0x23, 0x77, 0x10, 0x4d, 0x05,
	0x5b, 0x28, 0x72, 0x41, 0xc3, 0x55, 0xe8, 0xf1, 0x2a, 0xf4, 0xc1, 0x5d, 0xe5, 0xb7, 0xfb, 0x16,
	0x9a, 0xf3, 0x8d, 0xdc, 0xfd, 0xc9, 0x9c, 0xc7, 0x5e, 0xbc, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0xc9, 0x79, 0x55, 0x8f, 0xfd, 0x01, 0x00, 0x00,
}
